title: Adhiraiyan AI Blog by Mukesh Mithrakumar
email: mukesh@adhiraiyan.org
baseurl: ""
url: "https://www.adhiraiyan.org/"
twitter_username: MMithrakumar
github_username:  mukeshmithrakumar
author: Mukesh Mithrakumar

social:
  name: Mukesh Mithrakumar
  links:
    - https://twitter.com/MMithrakumar
    - https://www.facebook.com/adhiraiyan
    - https://www.linkedin.com/in/mukesh-mithrakumar
    - https://github.com/mukeshmithrakumar

image: /img/logo.PNG

# Gems
# gems: [jekyll-paginate, jekyll-sitemap, jekyll-algolia]

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-algolia

# Build settings
markdown: kramdown
paginate: 5

# Code highlight
highlighter: rouge


paginate_path: 'page:num/'
comments: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      author: "Mukesh"


algolia:
   application_id: 89JP3NPKQF
   index_name: post_NAME
   search_only_api_key: f4f60e0fc2427fe8735f2b87f0c8159c
