# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adhiraiyan AI Blog by Mukesh Mithrakumar
email: mukesh@mukeshmithrakumar.com
description: >-
  A Blog on all things AI, ranging from known deep learning topics to the broader software engineering principle. Check out the About Page for more topics and details
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MMithrakumar
github_username:  mukeshmithrakumar
author: Mukesh Mithrakumar

# social meta
logo: /img/logo.PNG
twitter:
  username: MMithrakumar
  card: summary

social:
  name: Mukesh Mithrakumar
  links:
    - https://twitter.com/MMithrakumar
    - https://www.facebook.com/mukeshmithrakumar
    - https://www.linkedin.com/in/BenBalter
    - https://github.com/mukeshmithrakumar

image: /img/logo.PNG

# Gems
gems: [jekyll-paginate, jekyll-seo-tag]

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
paginate: 5

paginate_path: 'page:num/'
comments: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      author: "Mukesh"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
